# Generated by Django 3.2.8 on 2021-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library_app', '0003_myuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Highlighted groups are the ones this user is a member of.', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Highlighted permissions are the ones this user is a member of.', to='auth.Permission'),
        ),
    ]
