# Generated by Django 3.2.8 on 2021-10-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20211022_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('isbn', models.CharField(max_length=200)),
                ('book_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('total_copies', models.IntegerField(default=0)),
                ('availables_copies', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
